"""Add ML dashboard tables

Revision ID: 002
Revises: 001
Create Date: 2024-11-22 03:26:26.074000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ml_roi_forecast table
    op.create_table('ml_roi_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('roi_forecast', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_roi_forecast_channel'), 'ml_roi_forecast', ['channel'], unique=False)
    op.create_index(op.f('ix_ml_roi_forecast_id'), 'ml_roi_forecast', ['id'], unique=False)
    
    # Create ml_roi_timeseries table
    op.create_table('ml_roi_timeseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('roi_actual', sa.Float(), nullable=True),
    sa.Column('conversion_actual', sa.Float(), nullable=True),
    sa.Column('roi_pred', sa.Float(), nullable=True),
    sa.Column('conversion_pred', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_roi_timeseries_channel'), 'ml_roi_timeseries', ['channel'], unique=False)
    op.create_index(op.f('ix_ml_roi_timeseries_id'), 'ml_roi_timeseries', ['id'], unique=False)
    
    # Create ml_reach_ctr_timeseries table
    op.create_table('ml_reach_ctr_timeseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('reach_actual', sa.Integer(), nullable=True),
    sa.Column('ctr_actual', sa.Float(), nullable=True),
    sa.Column('reach_pred', sa.Integer(), nullable=True),
    sa.Column('ctr_pred', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_reach_ctr_timeseries_channel'), 'ml_reach_ctr_timeseries', ['channel'], unique=False)
    op.create_index(op.f('ix_ml_reach_ctr_timeseries_id'), 'ml_reach_ctr_timeseries', ['id'], unique=False)
    
    # Create ml_budget_rec table
    op.create_table('ml_budget_rec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('roi_pred', sa.Float(), nullable=True),
    sa.Column('conversion_pred', sa.Float(), nullable=True),
    sa.Column('acquisition_cost', sa.Float(), nullable=True),
    sa.Column('recommended_budget', sa.Float(), nullable=True),
    sa.Column('budget_change_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_budget_rec_channel'), 'ml_budget_rec', ['channel'], unique=False)
    op.create_index(op.f('ix_ml_budget_rec_id'), 'ml_budget_rec', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_budget_rec_id'), table_name='ml_budget_rec')
    op.drop_index(op.f('ix_ml_budget_rec_channel'), table_name='ml_budget_rec')
    op.drop_table('ml_budget_rec')
    op.drop_index(op.f('ix_ml_reach_ctr_timeseries_id'), table_name='ml_reach_ctr_timeseries')
    op.drop_index(op.f('ix_ml_reach_ctr_timeseries_channel'), table_name='ml_reach_ctr_timeseries')
    op.drop_table('ml_reach_ctr_timeseries')
    op.drop_index(op.f('ix_ml_roi_timeseries_id'), table_name='ml_roi_timeseries')
    op.drop_index(op.f('ix_ml_roi_timeseries_channel'), table_name='ml_roi_timeseries')
    op.drop_table('ml_roi_timeseries')
    op.drop_index(op.f('ix_ml_roi_forecast_id'), table_name='ml_roi_forecast')
    op.drop_index(op.f('ix_ml_roi_forecast_channel'), table_name='ml_roi_forecast')
    op.drop_table('ml_roi_forecast')
    # ### end Alembic commands ###
